name: CustomEnchantUI
version: 1.0.0
author: LunarMoon72
api: 3.21.1
mcpe-protocal: 448
main: LunarMoon72\CustomEnchantUI\Main

commands:
   ceedit:
      description: Enchant the Item you Holding!
      permission: customenchantui.cmd
      
permissions:
   customenchantui.cmd:
       description: Test Perm
       default: op
